### ISSUE TITLE
add a complete example?

### ISSUE THREAD

**Issue by chirag04** [exponentjs/react-native-infinite-scroll-view#1]
Trying to use it, i get unexpected token (18:19) in infiniteScrollView.js

**Comment by chirag04** [comment]
@ide Wondering if this got anything to do with babel. 

Also, I'm using react-native master branch.

**Comment by ide** [comment]
Yes you should turn on several babel options. This is numbered as an 0.0.x release because I'm not supporting it outside of my own use cases yet.

**Comment by clintandrewhall** [comment]
Now that it's at 0.1.0, any chance you can post the babel options that need to be enabled to use this?  I'm just playing around with some other components and having it blow up right away kinda sucks.  Thanks in advance!

**Comment by ide** [comment]
We use these:

``` js
{
  "whitelist": [
    "es6.constants",
    "es6.modules",
    "es7.asyncFunctions",
    "es7.classProperties",
    "es7.decorators",
    "regenerator"
  ]
}
```

Some of these aren't necessary for this project like support for async functions. If you want to keep things simple just use `"stage": 0` and enable all modern syntax.

**Comment by bachvtuan** [comment]
I notice this lib is very poor document. Please give us full example how to load more item . Please

**Comment by ide** [comment]
The code is the documentation right now. If someone can write up a terse example we could add it to the README though.
