### ISSUE TITLE
A complete example?

### ISSUE THREAD

**Issue by varqasim** [exponentjs/react-native-infinite-scroll-view#17]
Would love if you'd post a complete example with maybe a `fetch()` that would show how to render the next rows when reaching the bottom of the ListView. It's kind of hard to grasp as a beginner.

**Comment by jvlobo** [comment]
I'd appreciate too a more complete example! :) thanks.

**Comment by faceyspacey** [comment]
+1

**Comment by nodkrot** [comment]
+1

**Comment by ruudkalis** [comment]
+1

**Comment by silentsiri** [comment]
+1
