### ISSUE TITLE
Why does it need to manually calculate when end is reached?

### ISSUE THREAD

**Issue by fabiosussetto** [exponentjs/react-native-infinite-scroll-view#18]
Hi, I was just wondering why you need to manually calculate when the list has reached the bottom, given that ListView has two built-in methods to do that:
- onEndReached
- onEndReachedThreshold

I was able to create an infinite scrolling list quite easily just by using those two props on a default ListView, are there any limitations of this approach?

Thanks!

**Comment by ide** [comment]
This component works with ScrollViews, not just ListViews. ScrollView doesn't define onEndReached. Hope that answers your question.
