### ISSUE TITLE
Use with https://github.com/exponentjs/react-native-invertible-scroll-view

### ISSUE THREAD

**Issue by satya164** [exponentjs/react-native-infinite-scroll-view#3]
Is it possible?

**Comment by ide** [comment]
I think so but haven't tried it. If you understand how they work I think you will be able to reason about how to compose them together.

**Comment by nodkrot** [comment]
Can you please provide an example? How can I provide two different ScrollViews to `renderScrollComponent` function?

**Comment by AustinAmoruso** [comment]
`renderScrollComponent={props => <InfiniteScrollView {...props}
                    renderScrollComponent={props => <InvertibleScrollView {...props} inverted />}
                />}`
