### ISSUE TITLE
Syntax Error in InfiniteScrollView.js: Unexpected Token (17:19)

### ISSUE THREAD

**Issue by agolovenko** [exponentjs/react-native-infinite-scroll-view#8]
Well, this is pretty much it. Looked inside your code and have no clue actually.
Maybe something to do with language level packaging options?
Tested on react-native 0.12.0 and 0.13.0-rc

**Comment by ide** [comment]
Can you try putting this in your .babelrc file?

``` json
{
  "whitelist": [
    "es7.classProperties",
    "es7.decorators"
  ]
}
```

**Comment by agolovenko** [comment]
thanks, worked like a charm=)
